language: c
compiler:
  - gcc
  - clang
os:
  - linux
before_install: ./install-dependencies.sh

script: ./bootstrap.sh && ./configure --with-cert-path="./invalid_cert" --with-private-key-path="./invalid_key" && make

